# Laravel API

### Create categoria
POST http://localhost:8000/api/categorias Http/1.1
Content-Type: application/json

{
  "nome": "Categoria 3"
}

### Create produto
POST http://localhost:8000/api/produtos Http/1.1
Content-Type: application/json

{
    "nome": "Produto 1",
    "descricao": "Descrição do produto 1",
    "preco": 10.00,
    "quantidade": 10,
   
}

### Get produtos
GET http://localhost:8000/api/produtos

### Get produto
GET http://localhost:8000/api/produtos/1

### Update produto
PUT http://localhost:8000/api/produtos/1 http/1.1
Content-Type: application/json

{
    "nome": "Produto 1 - updated",
    "descricao": "Descrição do produto 1",
    "preco": 10.00,
    "quantidade": 10,
    "categoria_id": 2
}

### Delete produto
DELETE http://localhost:8000/api/produtos/1

### Get categorias
GET http://localhost:8000/api/categorias

### Get categoria
GET http://localhost:8000/api/categorias/1

### Update categoria
PUT http://localhost:8000/api/categorias/1 http/1.1
Content-Type: application/json

{
  "nome": "Categoria 1 - updated"
}
